extends SceneTree
const Settings=preload("res://gameplay/control_settings.gd")
func _init() -> void:
	var settings=Settings.new();settings.path="/tmp/overtime-control-settings-test.cfg";settings.reset()
	assert(settings.bindings.slide==KEY_SHIFT and settings.bindings.dash==KEY_CTRL)
	assert(not settings.assign("slide",KEY_W).is_empty())
	assert(settings.assign("slide",KEY_C).is_empty());assert(settings.assign("reload",KEY_F).is_empty())
	assert(settings.assign("shoot",-MOUSE_BUTTON_MIDDLE).is_empty());settings.sensitivity=1.65;settings.automatic_reload=false;assert(settings.save()==OK)
	var loaded=Settings.new();loaded.path=settings.path;loaded.load_settings()
	assert(loaded.bindings.slide==KEY_C and loaded.bindings.reload==KEY_F and loaded.bindings.shoot==-MOUSE_BUTTON_MIDDLE)
	assert(is_equal_approx(loaded.sensitivity,1.65) and not loaded.automatic_reload)
	assert(InputMap.action_get_events("reload")[0].physical_keycode==KEY_F)
	loaded.reset();assert(loaded.bindings.slide==KEY_SHIFT and loaded.automatic_reload)
	assert(loaded.bindings.grapple == KEY_Q and loaded.bindings.skill_2 == KEY_E)
	assert(not loaded.assign("skill_2", KEY_Q).is_empty())
	assert(loaded.assign("skill_2", KEY_G).is_empty()); assert(loaded.save() == OK)
	settings.load_settings(); assert(settings.bindings.skill_2 == KEY_G)
	var legacy := ConfigFile.new(); var old: Dictionary = Settings.DEFAULTS.duplicate()
	old.erase("skill_2"); old.reload = KEY_E; old.grapple = KEY_F
	legacy.set_value("controls", "bindings", old); assert(legacy.save(settings.path) == OK)
	settings.load_settings()
	assert(settings.bindings.reload == KEY_E and settings.bindings.grapple == KEY_F)
	assert(settings.bindings.skill_2 != KEY_E and settings.bindings.skill_2 != KEY_F)
	print("PASS: defaults, conflict rejection, remap, mouse, save/load, reset");quit()
